2021-03-13 14:40:06,923 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:40:06,923 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:40:06,923 INFO    MainThread:24441 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144006-32qxqh5k/logs/debug.log
2021-03-13 14:40:06,923 INFO    MainThread:24441 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144006-32qxqh5k/logs/debug-internal.log
2021-03-13 14:40:06,924 INFO    MainThread:24441 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fcce1db0a00>
2021-03-13 14:40:06,924 INFO    MainThread:24441 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:40:06,925 INFO    MainThread:24441 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:40:06,925 INFO    MainThread:24441 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 112j2tj7
2021-03-13 14:40:06,927 INFO    MainThread:24441 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/112j2tj7
2021-03-13 14:40:06,927 INFO    MainThread:24441 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-13 14:40:06,928 INFO    MainThread:24441 [wandb_run.py:_restore():1418] restore
2021-03-13 14:40:07,207 INFO    MainThread:24441 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 591
  total_bytes: 591
}

2021-03-13 14:40:09,216 INFO    MainThread:24441 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4043
  total_bytes: 4043
}

2021-03-13 14:40:10,464 INFO    MainThread:24441 [wandb_run.py:_show_summary():1723] rendering summary
2021-03-13 14:40:10,465 INFO    MainThread:24441 [wandb_run.py:_show_history():1761] rendering history
2021-03-13 14:40:10,466 INFO    MainThread:24441 [wandb_run.py:_show_files():1790] logging synced files
2021-03-13 14:40:10,470 INFO    MainThread:24441 [wandb_init.py:init():416] starting backend
2021-03-13 14:40:10,471 INFO    MainThread:24441 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-13 14:40:10,473 INFO    MainThread:24441 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 14:40:10,483 INFO    MainThread:24441 [backend.py:ensure_launched():127] started backend process with pid: 24617
2021-03-13 14:40:10,488 INFO    MainThread:24441 [wandb_init.py:init():421] backend started and connected
2021-03-13 14:40:10,505 INFO    MainThread:24441 [wandb_init.py:init():461] updated telemetry
2021-03-13 14:40:10,506 INFO    MainThread:24441 [wandb_init.py:init():480] communicating current version
2021-03-13 14:40:11,247 INFO    MainThread:24441 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-13 14:40:11,248 INFO    MainThread:24441 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-13 14:40:11,514 INFO    MainThread:24441 [wandb_init.py:init():518] starting run threads in backend
2021-03-13 14:40:13,161 INFO    MainThread:24441 [wandb_run.py:_console_start():1476] atexit reg
2021-03-13 14:40:13,162 INFO    MainThread:24441 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-13 14:40:13,162 INFO    MainThread:24441 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-13 14:40:13,162 INFO    MainThread:24441 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-13 14:40:13,162 INFO    MainThread:24441 [wandb_init.py:init():542] run started, returning control to user process
2021-03-13 14:40:13,164 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:40:13,164 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:40:13,170 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:40:37,027 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:40:37,028 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:40:37,070 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:40:37,084 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:40:37,084 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:40:37,085 INFO    MainThread:24441 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144037-2g90thzz/logs/debug.log
2021-03-13 14:40:37,085 INFO    MainThread:24441 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144037-2g90thzz/logs/debug-internal.log
2021-03-13 14:40:37,085 INFO    MainThread:24441 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:40:37,085 INFO    MainThread:24441 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:40:37,085 INFO    MainThread:24441 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 32qxqh5k
2021-03-13 14:40:37,087 INFO    MainThread:24441 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/32qxqh5k
