2021-03-13 14:16:50,693 INFO    MainThread:24179 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:16:50,693 INFO    MainThread:24179 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:16:50,693 INFO    MainThread:24179 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_141650-28v5cppg/logs/debug.log
2021-03-13 14:16:50,693 INFO    MainThread:24179 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_141650-28v5cppg/logs/debug-internal.log
2021-03-13 14:16:50,694 INFO    MainThread:24179 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb8f058bd60>
2021-03-13 14:16:50,695 INFO    MainThread:24179 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:16:50,695 INFO    MainThread:24179 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:16:50,695 INFO    MainThread:24179 [wandb_init.py:init():416] starting backend
2021-03-13 14:16:50,695 INFO    MainThread:24179 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-13 14:16:50,714 INFO    MainThread:24179 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 14:16:50,722 INFO    MainThread:24179 [backend.py:ensure_launched():127] started backend process with pid: 24211
2021-03-13 14:16:50,726 INFO    MainThread:24179 [wandb_init.py:init():421] backend started and connected
2021-03-13 14:16:50,788 INFO    MainThread:24179 [wandb_init.py:init():461] updated telemetry
2021-03-13 14:16:50,788 INFO    MainThread:24179 [wandb_init.py:init():480] communicating current version
2021-03-13 14:16:51,544 INFO    MainThread:24179 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-13 14:16:51,546 INFO    MainThread:24179 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-13 14:16:51,879 INFO    MainThread:24179 [wandb_init.py:init():518] starting run threads in backend
2021-03-13 14:16:53,491 INFO    MainThread:24179 [wandb_run.py:_console_start():1476] atexit reg
2021-03-13 14:16:53,492 INFO    MainThread:24179 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-13 14:16:53,492 INFO    MainThread:24179 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-13 14:16:53,492 INFO    MainThread:24179 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-13 14:16:53,492 INFO    MainThread:24179 [wandb_init.py:init():542] run started, returning control to user process
2021-03-13 14:16:53,494 INFO    MainThread:24179 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:16:53,494 INFO    MainThread:24179 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:16:53,517 INFO    MainThread:24179 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:17:00,078 INFO    MainThread:24179 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:17:00,078 INFO    MainThread:24179 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:17:08,729 INFO    MainThread:24179 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:17:09,185 INFO    MainThread:24179 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:17:09,185 INFO    MainThread:24179 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:18:00,226 INFO    MainThread:24179 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:18:00,229 INFO    MainThread:24179 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:18:00,229 INFO    MainThread:24179 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:18:18,466 INFO    MainThread:24179 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:18:18,474 INFO    MainThread:24179 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:18:18,474 INFO    MainThread:24179 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:18:18,475 INFO    MainThread:24179 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_141818-2fl54uue/logs/debug.log
2021-03-13 14:18:18,475 INFO    MainThread:24179 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_141818-2fl54uue/logs/debug-internal.log
2021-03-13 14:18:18,475 INFO    MainThread:24179 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:18:18,475 INFO    MainThread:24179 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:18:18,475 INFO    MainThread:24179 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 28v5cppg
2021-03-13 14:18:18,477 INFO    MainThread:24179 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/28v5cppg
