2021-03-13 14:45:02,065 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:45:02,065 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:45:02,066 INFO    MainThread:24441 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144502-2j8rqrnj/logs/debug.log
2021-03-13 14:45:02,066 INFO    MainThread:24441 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144502-2j8rqrnj/logs/debug-internal.log
2021-03-13 14:45:02,066 INFO    MainThread:24441 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fcd04ab3070>
2021-03-13 14:45:02,066 INFO    MainThread:24441 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:45:02,066 INFO    MainThread:24441 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:45:02,066 INFO    MainThread:24441 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 2g90thzz
2021-03-13 14:45:02,067 INFO    MainThread:24441 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/2g90thzz
2021-03-13 14:45:02,068 INFO    MainThread:24441 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-13 14:45:02,068 INFO    MainThread:24441 [wandb_run.py:_restore():1418] restore
2021-03-13 14:45:02,348 INFO    MainThread:24441 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 591
  total_bytes: 591
}

2021-03-13 14:45:04,362 INFO    MainThread:24441 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3926
  total_bytes: 3926
}

2021-03-13 14:45:05,602 INFO    MainThread:24441 [wandb_run.py:_show_files():1790] logging synced files
2021-03-13 14:45:05,607 INFO    MainThread:24441 [wandb_init.py:init():416] starting backend
2021-03-13 14:45:05,607 INFO    MainThread:24441 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-13 14:45:05,610 INFO    MainThread:24441 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 14:45:05,621 INFO    MainThread:24441 [backend.py:ensure_launched():127] started backend process with pid: 24678
2021-03-13 14:45:05,625 INFO    MainThread:24441 [wandb_init.py:init():421] backend started and connected
2021-03-13 14:45:05,642 INFO    MainThread:24441 [wandb_init.py:init():461] updated telemetry
2021-03-13 14:45:05,643 INFO    MainThread:24441 [wandb_init.py:init():480] communicating current version
2021-03-13 14:45:06,386 INFO    MainThread:24441 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-13 14:45:06,387 INFO    MainThread:24441 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-13 14:45:06,655 INFO    MainThread:24441 [wandb_init.py:init():518] starting run threads in backend
2021-03-13 14:45:08,327 INFO    MainThread:24441 [wandb_run.py:_console_start():1476] atexit reg
2021-03-13 14:45:08,328 INFO    MainThread:24441 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-13 14:45:08,328 INFO    MainThread:24441 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-13 14:45:08,328 INFO    MainThread:24441 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-13 14:45:08,329 INFO    MainThread:24441 [wandb_init.py:init():542] run started, returning control to user process
2021-03-13 14:45:08,331 INFO    MainThread:24441 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-13 14:45:08,331 INFO    MainThread:24441 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 14:45:23,672 INFO    MainThread:24441 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-13 14:45:23,683 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 14:45:23,683 INFO    MainThread:24441 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 14:45:23,683 INFO    MainThread:24441 [wandb_init.py:_log_setup():334] Logging user logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144523-70u3tarl/logs/debug.log
2021-03-13 14:45:23,683 INFO    MainThread:24441 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/amalota/Documents/mgr/DRL-XAI-POC/wandb/run-20210313_144523-70u3tarl/logs/debug-internal.log
2021-03-13 14:45:23,684 INFO    MainThread:24441 [wandb_init.py:init():367] calling init triggers
2021-03-13 14:45:23,684 INFO    MainThread:24441 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 14:45:23,684 INFO    MainThread:24441 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 2j8rqrnj
2021-03-13 14:45:23,685 INFO    MainThread:24441 [wandb_run.py:finish():1135] finishing run malota/deep-rl-tf2/2j8rqrnj
